CREATE INDEX HF_JOB_EXPIREAT ON HF_JOB(EXPIRE_AT);
CREATE INDEX HF_JOB_STATEID ON HF_JOB(STATE_ID);
CREATE INDEX HF_COUNTER_KEY ON HF_COUNTER(KEY);
CREATE INDEX HF_JOB_PARAMETER_JOBIDNAME ON HF_JOB_PARAMETER(JOB_ID, NAME);
CREATE INDEX HF_JOB_QUEUE_JOBID ON HF_JOB_QUEUE(JOB_ID);
CREATE INDEX HF_JOB_QUEUE_QUEUE ON HF_JOB_QUEUE(QUEUE);
CREATE INDEX HF_JOB_STATE_JOBID ON HF_JOB_STATE(JOB_ID);
CREATE INDEX HF_LIST_KEY ON HF_LIST(KEY);